name: Open-CE Feedstock PR Tests

on:
  pull_request:
    branches: [$default-branch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: "3.7"
      - uses: open-ce/open-ce/.github/actions/feedstock-pr@master
